import "./globals.css";
import { Inter } from "next/font/google";
import NavBar from "../components/NavBar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "al-quran",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="">{children}</div>
        <div className="color-bg font-bold text-white p-16 text-center">
          <p>ساخته شده توسط علی جواد حیدری برای مسابقات 1402 خرداد</p>
        </div>
      </body>
    </html>
  );
}
